# Generated by Django 6.1 on 2026-08-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode_updateunverifiedemailcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateUnverifiedEmailCode',
        ),
    ]
