# Generated by Django 6.1 on 2026-08-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
    ]
